// DO NOT MODIFY MANUALLY — generated by scripts/generate.js
//
// Protobuf codec for the PostgreSQL 16 parse tree.

import { fromBinary, fromJson, toBinary, toJson } from '@bufbuild/protobuf';
import { ParseResultSchema } from './gen/pg_query_pb.js';
import type { ParseTree } from '../types.js';

export const PG_VERSION = 16;

/**
 * Encode a parse tree — the JSON that `libpg-query`'s `parse()` returns — into
 * the protobuf wire format that `pg_query_deparse_protobuf()` expects.
 *
 * The tree's JSON field names (`SelectStmt`, `targetList`, …) are the
 * `json_name` annotations in pg_query.proto, which protobuf-es honours.
 *
 * Decoding is strict on purpose. A misspelled field or a bogus enum value in a
 * hand-edited tree throws here rather than being dropped on the floor and
 * deparsed into quietly wrong SQL.
 *
 * @throws if `tree` doesn't match the PostgreSQL 16 schema
 */
export function encodeParseTree(tree: ParseTree): Uint8Array {
  const message = fromJson(ParseResultSchema, tree as never);
  return toBinary(ParseResultSchema, message);
}

/** Decode a protobuf-encoded parse tree back into the JSON `parse()` shape. */
export function decodeParseTree(bytes: Uint8Array): ParseTree {
  return toJson(ParseResultSchema, fromBinary(ParseResultSchema, bytes)) as ParseTree;
}

export { ParseResultSchema };
