#!/usr/bin/env node
//
// Regenerates the protobuf-es schemas under src/vNN/ from the checked-in
// protos/NN/pg_query.proto files at the repo root.
//
// This is a deliberate dev step: the output is committed, so neither CI nor
// consumers need a protobuf toolchain. Re-run it after `pnpm run fetch:protos`
// picks up a new libpg_query release.

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const packageDir = path.join(__dirname, '..');
const repoRoot = path.join(packageDir, '..');
const protosDir = path.join(repoRoot, 'protos');
const srcDir = path.join(packageDir, 'src');

// .npmrc sets node-linker=hoisted, so the bins usually land in the root
// node_modules rather than the package's own. Check both.
const binDirs = [
  path.join(packageDir, 'node_modules', '.bin'),
  path.join(repoRoot, 'node_modules', '.bin'),
];
const binDir = binDirs.find((dir) => fs.existsSync(path.join(dir, 'buf')));

function discoverVersions() {
  return fs
    .readdirSync(protosDir)
    .filter((entry) => fs.existsSync(path.join(protosDir, entry, 'pg_query.proto')))
    .sort((a, b) => Number(a) - Number(b));
}

// The per-version entrypoint. Everything protobuf-es is kept behind this
// facade so consumers only ever see Uint8Array in and JSON out — that keeps
// them off `moduleResolution: node16`, which @bufbuild/protobuf's subpath
// exports would otherwise force on them.
function versionIndex(version) {
  return `// DO NOT MODIFY MANUALLY — generated by scripts/generate.js
//
// Protobuf codec for the PostgreSQL ${version} parse tree.

import { fromBinary, fromJson, toBinary, toJson } from '@bufbuild/protobuf';
import { ParseResultSchema } from './gen/pg_query_pb.js';
import type { ParseTree } from '../types.js';

export const PG_VERSION = ${version};

/**
 * Encode a parse tree — the JSON that \`libpg-query\`'s \`parse()\` returns — into
 * the protobuf wire format that \`pg_query_deparse_protobuf()\` expects.
 *
 * The tree's JSON field names (\`SelectStmt\`, \`targetList\`, …) are the
 * \`json_name\` annotations in pg_query.proto, which protobuf-es honours.
 *
 * Decoding is strict on purpose. A misspelled field or a bogus enum value in a
 * hand-edited tree throws here rather than being dropped on the floor and
 * deparsed into quietly wrong SQL.
 *
 * @throws if \`tree\` doesn't match the PostgreSQL ${version} schema
 */
export function encodeParseTree(tree: ParseTree): Uint8Array {
  const message = fromJson(ParseResultSchema, tree as never);
  return toBinary(ParseResultSchema, message);
}

/** Decode a protobuf-encoded parse tree back into the JSON \`parse()\` shape. */
export function decodeParseTree(bytes: Uint8Array): ParseTree {
  return toJson(ParseResultSchema, fromBinary(ParseResultSchema, bytes)) as ParseTree;
}

export { ParseResultSchema };
`;
}

function generate() {
  if (!binDir) {
    console.error('buf not found — run `pnpm install` at the repo root first.');
    process.exit(1);
  }

  const versions = discoverVersions();
  console.log(`Generating protobuf-es schemas for: ${versions.join(', ')}\n`);

  for (const version of versions) {
    const outDir = path.join(srcDir, `v${version}`);
    fs.rmSync(path.join(outDir, 'gen'), { recursive: true, force: true });
    fs.mkdirSync(outDir, { recursive: true });

    execFileSync(path.join(binDir, 'buf'), ['generate', path.join(protosDir, version), '-o', outDir], {
      cwd: packageDir,
      stdio: 'inherit',
      env: { ...process.env, PATH: `${binDir}${path.delimiter}${process.env.PATH}` },
    });

    fs.writeFileSync(path.join(outDir, 'index.ts'), versionIndex(version));
    console.log(`  ✓ v${version}`);
  }

  console.log('\n✅ Schema generation completed!');
}

generate();
